### ISSUE TITLE
Workplan->Issues-> Showing active even after getting deactivated

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#2258] opened 2024-05-17 21:51 UTC
**Overview**
The issue in workplan showing active even after it got deactivated
**Steps to reproduce**
1. Go to workplan
2. Go to Issue tab
3. Add one issue
4. Edit the newly added issue by clicking the pen icon in the accordion
5. Deactivate the issue and hit save
6. Refresh and press edit button again and see the sate of the issue

**Expectation**
The issue should be shown deactivated

**Actual**
The issue shows active

**Comment by jadmnsaad** [comment] 2024-05-31 23:33
@dinesh-aot @Connor1892 @maria-kuzmenko 

I can't replicate this, I can see that the issue is display the inactive state.

<img width="854" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a77bd5f42f7f320be124d584c32804cbc48454a1/image.png" alt="image.png" />

Can you do it maybe in dev or test and send a link here of the workplan where that is happening?

**Comment by Connor1892** [comment] 2024-06-13 21:43
@jadmsaadaot we cannot re-activate a deactivated issue!

**Comment by jadmnsaad** [comment] 2024-06-14 16:31
@Connor that's out of scope for this ticket no?

**Closed as completed** 2024-06-14 17:11 UTC
Labels: bug

**Comment by maria-kuzmenko** [comment] 2024-06-14 17:14
@Connor1892 , closed this one, opened another one for Jad - https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/2335
