### ISSUE TITLE
Add more milestone types and correct the existing PECP related milestones in the table

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#92] opened 2022-07-19 12:04 UTC
**Overview**
Create three more milestones
- PECP Open
- PECP Coming
- PECP Closing

Find the corresponding milestones in the milestones table and correct the milestone_id column with the new value

**Comment by salabh-aot** [comment] 2022-07-21 05:38
Closing this ticket as it is a duplicate of [#96](https://app.zenhub.com/workspaces/epicflow-6294f8278397390011a5d2f2/issues/bcgov/epic-flow/96)

**Closed by salabh-aot** 2022-07-21 05:38 UTC
