### ISSUE TITLE
Nation Tab - Add Nation button

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1905] opened 2024-02-28 17:52 UTC
**Describe the bug**
the add nation button disables after a single nation is added

**To Reproduce**
1. Go to any work's nation tab
2. Click on add nation
3. add a nation

**Expected behavior**
the add nation button should not be disabled for anyone who is assigned to that team, or for superusers & above

**Screenshots**

**Additional context**

**Comment by jadmnsaad** [comment] 2024-02-29 21:33
@Connor1892  I tried this and I could not reproduce the issue, could you please try again and if it's still not working let's try it in a meeting?

**Comment by Connor1892** [comment] 2024-02-29 22:24
@jadmsaadaot it's happening in Prod. so maybe it's been fixed by something that hasn't hit that environment yet?

If you're a viewer on a team. after the 1st First Nation is added the button disables.

**Comment by jadmnsaad** [comment] 2024-03-01 17:22
@dinesh-aot it seems this is something happening in prod but not in dev. Might have been fixed. Can you confirm please if we can close this?

**Closed as not planned** 2024-03-04 18:44 UTC
Labels: bug, P0, BreakFix
